--뷰는 ONLY 조회용으로만 사용할것! (select만 가능)

CREATE VIEW PERSONAL_VIEW (MEMBER_TYPE, MEMBER_ID,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,
PER_TALK,PER_AGE,PER_ADDRESS,PER_SEX,PER_PHOTO)
AS(
SELECT MEMBER_TYPE, MEMBER_ID,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,
PER_TALK,PER_AGE,PER_ADDRESS,PER_SEX,PER_PHOTO FROM
(SELECT MEMBER_TYPE, MEMBER_ID,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL FROM MEMBER_INFO) 
INNER JOIN (SELECT PER_ID,PER_TALK,PER_AGE,PER_ADDRESS,PER_SEX,PER_PHOTO FROM PERSONAL_INFO)
ON MEMBER_ID= PER_ID
)


-- Table 명		PERSONAL_VIEW				개인이 내정보 볼때 보여줄것 (1번빼고 ) + 구인검색에서 이력서 정보 보여줄때 사용			
--No	Column 명	한글명 	자료형	NULL	Key	비고 / 설명			
--1	MEMBER_TYPE	타입코드	NUMBER	N	PK	0 개인회원 1 기업회원 (쓸지말지 생각중)			
--2	MEMBER_ID	아이디	VARCHAR2(100)	N	PK	회원번호랑 같은것으로 부여			
--3	MEMBER_NAME	이름	VARCHAR2(100)	N		이름			
--4	MEMBER_PHONE	폰번호	VARCHAR2(200)	N					
--5	MEMBER_EMAIL	이메일	VARCHAR2(100)	N					
--6	PER_ID	개인회원id	VARCHAR2(100)	N	FK(MEMBER_ID)	회원id에 대한키			
--7	PER_TALK	개인소갯말	VARCHAR2(400)	N		100자 이내 간단한 소갯말			
--8	PER_AGE	나이	NUMBER	N					
--9	PER_ADDRESS	개인주소	VARCHAR2(400)	N		주소 API로 			
--10	PER_SEX	성별	VARCHAR2(20)	N		남,녀			
--11	PER_PHOTO	사진파일이름	VARCHAR2(200)	N	디폴트 NONE	사진파일이름(확장자 포함) ,NONE일경우 사진파일이 등록안된경우			
								

CREATE VIEW COMPANY_VIEW (MEMBER_TYPE, MEMBER_ID,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,
COM_NUMBER,COM_NAME,COM_ADDRESS,COM_CEO,COM_PHONE)
AS(
SELECT MEMBER_TYPE, MEMBER_ID,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,
COM_NUMBER,COM_NAME,COM_ADDRESS,COM_CEO,COM_PHONE FROM
(SELECT MEMBER_TYPE, MEMBER_ID,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL FROM MEMBER_INFO) 
INNER JOIN (SELECT COM_NUMBER,COM_NAME,COM_ADDRESS,COM_CEO,COM_PHONE,COM_ID FROM COM_INFO)
ON MEMBER_ID= COM_ID
)
SELECT * FROM  COMPANY_VIEW;
-- Table 명		COMPANY_VIEW				회사가 내정보볼때 보여줄것(1번빼고)			
--No	Column 명	한글명 	자료형	NULL	Key	비고 / 설명			
--1	MEMBER_TYPE	타입코드	NUMBER	N	PK	0 개인회원 1 기업회원 (쓸지말지 생각중)			
--2	MEMBER_ID	아이디	VARCHAR2(100)	N	PK	회원번호랑 같은것으로 부여			
--3	MEMBER_NAME	이름	VARCHAR2(100)	N		이름			
--4	MEMBER_PHONE	폰번호	VARCHAR2(200)	N					
--5	MEMBER_EMAIL	이메일	VARCHAR2(100)	N					
--6	COM_NUMBER	사업자등록번호	VARCHAR2(200)	N					
--7	COM_NAME	회사/점포명	VARCHAR2(200)	N					
--8	COM_ADRESS	회사/점포주소	VARCHAR2(400)	N					
--9	COM_CEO	대표자명	VARCHAR2(100)	N					
--10	COM_PHONE	회사전화번호	VARCHAR2(100)	N					